### ISSUE TITLE
This is digital signal transmitter with 50% of error correction payload?

### ISSUE THREAD

**Issue by ropucyka** [aicodix/shredpix#3]
Then why transmission is time and size limited?
I want to send my original photo by audio via this digital method.

Look:
Better send via your app _RAR_ archive file with include 50% of Recovery Record (which based on Reed-Solomon codes) and then recover it in background, instead of your 50% bandwidht overload by duplicating data.

No file browser, non comfortable options menu. Tested it, and i can send PNG only very small or with potato quality.
Useless app with not realized COFDMTV potential.

Anyway, with respect for your work. SSTV app coders helping with transmission photos from anals of this world to comfortable place.

**Comment by xdsopl** [comment]
The intention of these apps was to play with ideas I had for a long time and to develop a digital picture transmission alternative to SSTV.
Why do you say this app is useless?
There is no other app on the Google Play Store that comes even close to what my apps are capable off.

**Comment by ropucyka** [comment]
As i say, i'm true respect your efforts. And your app is unical not in Google Play Store only, but in world over.

You can make it more better by extend functionality of app and logic.

**Comment by xdsopl** [comment]
The problem is not easy to solve if we want something robust. Rest assured, I am working on it.
